version: 2

sources:
  - name: public
    tables:
      - name: customers
      - name: product
      - name: product_category
      - name: suppliers
      - name: coupons
      - name: orders
      - name: order_items
      - name: login_attempt_history

models:
  - name: fact_orders
    columns:
      - name: order_id
        tests:
          - not_null
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id

  - name: fact_login_attempts
    columns:
      - name: attempt_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null

  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: dim_products
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: dim_suppliers
    columns:
      - name: supplier_id
        tests:
          - unique
          - not_null

  - name: dim_categories
    columns:
      - name: category_id
        tests:
          - unique
          - not_null

  - name: dim_coupons
    columns:
      - name: coupon_id
        tests:
          - unique
          - not_null

